// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mihjsxluelbpdbdkviph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1paGpzeGx1ZWxicGRiZGt2aXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDkwMDgsImV4cCI6MjA3MTU4NTAwOH0.I21AckUKh9yWEoroqhm1n0HGJO3AhpizbaQvsv_ZpKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});